basePath: /v1
definitions:
  redirect.getRedirectBySlugResponse:
    properties:
      slug:
        type: string
      url:
        type: string
    type: object
  redirect.postRedirectRequest:
    properties:
      url:
        type: string
    type: object
  redirect.postRedirectResponse:
    properties:
      slug:
        type: string
      url:
        type: string
    type: object
  redirect.redirectErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: cutt.ovh Backend
  title: cutt.ovh Backend API
  version: "1.0"
paths:
  /redirect:
    post:
      consumes:
      - application/json
      description: Adds new short url redirect
      operationId: postRedirect
      parameters:
      - description: Set up url to shorten
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/redirect.postRedirectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/redirect.postRedirectResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/redirect.redirectErrorResponse'
      summary: Add redirect
      tags:
      - redirect
  /redirect/{slug}:
    get:
      consumes:
      - application/json
      description: Gets shortened url info by slug
      operationId: getRedirectBySlug
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/redirect.getRedirectBySlugResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/redirect.redirectErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/redirect.redirectErrorResponse'
      summary: Get redirect
      tags:
      - redirect
  /redirect/{slug}/execute:
    get:
      consumes:
      - application/json
      description: Executes redirect to original url
      operationId: getRedirectExecute
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "301":
          description: ""
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/redirect.redirectErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/redirect.redirectErrorResponse'
      summary: Get execute redirect
      tags:
      - redirect
swagger: "2.0"
